apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wall-e-frontend
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        "f:spec":
          "f:template":
            "f:spec":
              "f:containers":
                'k:{"name":"wall-e-client-sha256-1"}':
      manager: GoogleCloudConsole
      operation: Update
      time: "2021-02-22T07:18:14Z"
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        "f:metadata":
          "f:annotations":
      manager: kube-controller-manager
      operation: Update
      time: "2021-02-23T08:26:07Z"
  name: wall-e-frontend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wall-e-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wall-e-frontend
    spec:
      containers:
        - image: gcr.io/wall-e-305307/github.com/akifgulmus/wall-e
          imagePullPolicy: IfNotPresent
          name: wall-e-client-sha256-1
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: wall-e-frontend
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        "f:spec":
          "f:ports":
            .: {}
            'k:{"port":80,"protocol":"TCP"}':
      manager: GoogleCloudConsole
      operation: Update
      time: "2021-02-22T07:23:58Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        "f:metadata":
          "f:finalizers":
            .: {}
            'v:"service.kubernetes.io/load-balancer-cleanup"': {}
        "f:status":
          "f:loadBalancer":
            "f:ingress": {}
      manager: kube-controller-manager
      operation: Update
      time: "2021-02-22T07:24:31Z"
  name: wall-e-frontend-service
  namespace: default
spec:
  clusterIP: 10.16.5.203
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 32473
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: wall-e-frontend
  sessionAffinity: None
  type: LoadBalancer
